"""数据模型模块"""

from .schemas import (
    TripRequest,
    POISearchRequest,
    RouteRequest,
    Location,
    Attraction,
    Meal,
    Hotel,
    DayPlan,
    WeatherInfo,
    Budget,
    TripPlan,
    TripPlanResponse,
    POIInfo,
    POISearchResponse,
    RouteInfo,
    RouteResponse,
    WeatherResponse,
    ErrorResponse,
)

from .state import (
    AttractionCandidate,
    HotelCandidate,
    RestaurantCandidate,
    SearchStrategy,
    CuratedAttractions,
    MealAssignment,
    DayAssignment,
    ItineraryDraftSkeleton,
    TripPlannerState,
)

__all__ = [
    # Schemas
    "TripRequest",
    "POISearchRequest",
    "RouteRequest",
    "Location",
    "Attraction",
    "Meal",
    "Hotel",
    "DayPlan",
    "WeatherInfo",
    "Budget",
    "TripPlan",
    "TripPlanResponse",
    "POIInfo",
    "POISearchResponse",
    "RouteInfo",
    "RouteResponse",
    "WeatherResponse",
    "ErrorResponse",
    # State & Candidates
    "AttractionCandidate",
    "HotelCandidate",
    "RestaurantCandidate",
    "SearchStrategy",
    "CuratedAttractions",
    "MealAssignment",
    "DayAssignment",
    "ItineraryDraftSkeleton",
    "TripPlannerState",
]
